name: fourth-workflow
on: push
jobs:
    job: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout test
              run: pwd
            - name: print test
              run: |
                echo "started.."
                echo "end"    