name: test project
on: push
jobs:
    job1:
        runs-on: ubuntu_latest
        steps: 
            - name: Get code
              uses: actions/checkout@v4
            - name: Print message
              run: echo "Good Day!"  

